// County ILP / EFC / THP contacts, straight from the CDSS list. Generated by a
// script from the page below on the date shown; the app links back to the live page
// so a stale phone number is one tap from the current one.
export const COUNTY_SOURCE = { name: "CDSS - County Contacts for EFC, THP, and ILP", url: "https://www.cdss.ca.gov/inforesources/foster-care/county-contacts-for-efc-thp-and-ilp", retrieved: "2026-09-07" };

export interface CountyContact { programs: string; name: string; title: string; address: string; email: string; phone: string; note: string }
export interface CountyEntry { county: string; confirmed: string; contacts: CountyContact[] }

export const counties: CountyEntry[] = [
  {
    "county": "Alameda",
    "confirmed": "Confirmed 9/3/2026",
    "contacts": [
      {
        "programs": "THP",
        "name": "Devyn Taylor",
        "title": "Program Manager",
        "address": "1111 Jackson St, Oakland, CA 94612",
        "email": "taylode@acgov.org",
        "phone": "(510) 268-2433",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "William Nguyen, PhD",
        "title": "Division Director, Permanent Pathways & Benefit Services",
        "address": "1111 Jackson St, Oakland, CA 94612",
        "email": "nguyew@acgov.org",
        "phone": "(510) 268-2721",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Michelle Love",
        "title": "Assistant Agency Director, Dept. of Children & Family Services",
        "address": "1111 Jackson St, Oakland, CA 94612",
        "email": "lovemi@acgov.org",
        "phone": "(510) 268-2727",
        "note": ""
      },
      {
        "programs": "EFC",
        "name": "Jon Pettigrew",
        "title": "Program Manager",
        "address": "1111 Jackson St, Oakland, CA 94612",
        "email": "pettij@acgov.org",
        "phone": "(510) 268-4298",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Shante Spears",
        "title": "ILP Coordinator",
        "address": "675 Hegenberger Road, Suite 100 Oakland, CA 94621",
        "email": "spears@acgov.org",
        "phone": "(510) 667-7610",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Jeff Samp",
        "title": "Program Manager",
        "address": "675 Hegenberger Road, Suite 100 Oakland, CA 94621",
        "email": "SAMPJ@acgov.org",
        "phone": "(510) 667-7682",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Mia Buckner-Preston, M.A.",
        "title": "Division Director, Resource Family Approval, Placement & ILP Support Services",
        "address": "1111 Jackson St, Oakland, CA 94612",
        "email": "bucknm@acgov.org",
        "phone": "(510) 780-8937",
        "note": ""
      },
      {
        "programs": "Alameda County ILP Website",
        "name": "Alameda County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Alpine",
    "confirmed": "Confirmed 4/2/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Scott Kent",
        "title": "Social Worker III",
        "address": "75-A Diamond Valley Rd. Markleeville, CA 96120",
        "email": "skent@alpinecountyca.gov",
        "phone": "(530) 694-2235, ext. 261",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Patty Baker",
        "title": "Integrated Caseworker III",
        "address": "75-A Diamond Valley Rd. Markleeville, CA 96120",
        "email": "pbaker@alpinecountyca.gov",
        "phone": "(530) 694-2235, ext. 234",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Jennifer Wild-Ciavaglia",
        "title": "Social Worker IV",
        "address": "75-A Diamond Valley Rd. Markleeville, CA 96120",
        "email": "jciavaglia@alpinecountyca.gov",
        "phone": "(530) 694-2235, ext. 268",
        "note": ""
      }
    ]
  },
  {
    "county": "Amador",
    "confirmed": "Confirmed 3/24/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Lori Halvorson",
        "title": "Programs Director",
        "address": "Nexus Youth & Family Services 601 Court St., Suite 210 Jackson, CA 95642",
        "email": "lhalvorson@nexusyfs.org",
        "phone": "(209) 257-1980, ext. 107",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Nadine Magana",
        "title": "Administrative Director",
        "address": "Nexus Youth & Family Services 601 Court St., Suite 210 Jackson, CA 95642",
        "email": "nmagana@nexusyfs.org",
        "phone": "(209) 257-1980, ext. 102",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Gianna Dillon",
        "title": "ILP Coordinator",
        "address": "Nexus Youth & Family Services 601 Court St., Suite 210 Jackson, CA 95642",
        "email": "gdillon@nexusyfs.org",
        "phone": "(209) 257-1980, ext. 103",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Butte",
    "confirmed": "Updated 6/19/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Chico office main",
        "title": "www.ncyfp.org",
        "address": "Youth and Family Programs Office 2577 California Park Dr Chico, CA 95928",
        "email": "",
        "phone": "(530) 893-1614",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Crystal Hutchison",
        "title": "Coordinator",
        "address": "PO Box 1649 Oroville, CA 95965",
        "email": "chutchison@buttecounty.net",
        "phone": "",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Annaliesa Batts",
        "title": "ILP Support",
        "address": "PO Box 1649 Oroville, CA 95965",
        "email": "abatts@buttecounty.net",
        "phone": "(530) 552-6220",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Michelle Dahlgren",
        "title": "Coordinator",
        "address": "Youth and Family Programs Office 2577 California Park Dr Chico, CA 95928",
        "email": "madahlgren@youthandfamily.info",
        "phone": "(530) 518-8313",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Aireanna Reposa",
        "title": "ILP Coordinator",
        "address": "Youth and Family Programs Office 2577 California Park Dr Chico, CA 95928",
        "email": "areposa@youthandfamily.info",
        "phone": "(530) 570-6808",
        "note": ""
      },
      {
        "programs": "Butte County ILP web page",
        "name": "Butte County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "Butte County Transitional Housing Program (THP) web page",
        "name": "Butte County THP web page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Calaveras",
    "confirmed": "Updated 4/29/2026",
    "contacts": [
      {
        "programs": "EFC, THP",
        "name": "Lee Kimball",
        "title": "Housing Program Manager",
        "address": "509 E St. Charles St. San Andreas, CA 95249",
        "email": "lkimball@calaverascounty.gov",
        "phone": "(209) 754-6734",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Kolby Epperson",
        "title": "Program Manager, Social Services",
        "address": "509 E St. Charles St. San Andreas, CA 95249",
        "email": "KEpperson@calaverascounty.gov",
        "phone": "(209) 768-7585",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Melissa Harvey",
        "title": "Foster Youth Services Manager",
        "address": "185 S Main St. Angels Camp, CA 95222",
        "email": "mharvey@ccoe.k12.ca.us",
        "phone": "(209) 736-6059",
        "note": ""
      },
      {
        "programs": "Calaveras County ILP Website",
        "name": "Calaveras County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Colusa",
    "confirmed": "Updated 6/26/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Jaynae Grass",
        "title": "Program Manager II",
        "address": "251 E. Webster St Colusa, CA 95932",
        "email": "jaynae.grass@countyofcolusa.com",
        "phone": "(530) 458-0293",
        "note": ""
      },
      {
        "programs": "Colusa IILP Web Information",
        "name": "Colusa County Child Welfare Services",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Contra Costa",
    "confirmed": "Confirmed 3/23/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Timothy Hamp",
        "title": "Assistant ILSP Coordinator",
        "address": "1875 Arnold Drive Suite 200 Martinez, CA 94553",
        "email": "hampt@ehsd.cccounty.us",
        "phone": "(925) 655-0253",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Don Graves",
        "title": "ILSP Coordinator Supervisor",
        "address": "1875 Arnold Drive Suite 200 Martinez, CA 94553",
        "email": "dgraves@ehsd.cccounty.us",
        "phone": "(925) 655-0254",
        "note": ""
      },
      {
        "programs": "Contra Costa County ILP Website",
        "name": "Contra Costa County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Del Norte",
    "confirmed": "Updated 4/27/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Lila Honahni",
        "title": "Social Worker Supervisor",
        "address": "880 Northcrest Dr. Crescent City, CA 95531",
        "email": "lila.honahni@co.del-norte.ca.us",
        "phone": "(707) 464-3191 ext. 2717",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Nancy Blankenship",
        "title": "Social Worker",
        "address": "880 Northcrest Dr. Crescent City, CA 95531",
        "email": "nblankenship@co.del-norte.ca.us",
        "phone": "(707) 464-3191 ext. 2730",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Katy Hampson",
        "title": "Program Manager",
        "address": "880 Northcrest Dr. Crescent City, CA 95531",
        "email": "katy.hampson@co.del-norte.ca.us",
        "phone": "(707) 464-3191",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "EL DORADO",
        "name": "No ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": "Updated 4/27/2026"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Andrea Hunt",
        "title": "Social Worker Program Supervisor II",
        "address": "3057 Briw Road, Suite A Placerville, CA 95667",
        "email": "andrea.hunt@edcgov.us",
        "phone": "(530) 295-6924",
        "note": "Primary contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "David Brownstein",
        "title": "Program Manager I",
        "address": "3057 Briw Road, Suite A Placerville, CA 95667",
        "email": "david.brownstein@edcgov.us",
        "phone": "(530) 294-6928",
        "note": "Secondary / backup contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Jordan Harrington",
        "title": "AB12 Social Worker",
        "address": "3057 Briw Road, Suite A Placerville, CA 95667",
        "email": "jordan.harrington@edcgov.us",
        "phone": "(530) 642-7311",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Fresno",
    "confirmed": "Updated 3/23/2026",
    "contacts": [
      {
        "programs": "ILP emailbox and phone number",
        "name": "",
        "title": "",
        "address": "",
        "email": "CWSILP@fresnocountyca.gov",
        "phone": "(559) 600-6689",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Cirilo Medina",
        "title": "ILP / AB12 Housing Liaison",
        "address": "380 W Ashlan Ave. Clovis, CA 93612",
        "email": "cimedina@fresnocountyca.gov",
        "phone": "(559) 600-1098",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Melissa Chacon",
        "title": "ILP / AB12 Housing Supervisor",
        "address": "380 W Ashlan Ave. Clovis, CA 93612",
        "email": "chacom@fresnocountyca.gov",
        "phone": "(559) 600-2265",
        "note": ""
      },
      {
        "programs": "ILP, EFC",
        "name": "Katie Wettlaufer",
        "title": "ILP / AB 12 Social Worker/ Out of County Coordinator",
        "address": "380 W Ashlan Ave. Clovis, CA 93612",
        "email": "wettlk@fresnocountyca.gov",
        "phone": "(559) 600-1769",
        "note": ""
      },
      {
        "programs": "ILP, EFC",
        "name": "Sanford Thomas",
        "title": "ILP / AB 12 Social Worker",
        "address": "380 W Ashlan Ave. Clovis, CA 93612",
        "email": "thomasg@fresnocountyca.gov",
        "phone": "(559) 600-2465",
        "note": ""
      },
      {
        "programs": "ILP, EFC",
        "name": "Casey Arashsiro",
        "title": "ILP / EFC Social Worker",
        "address": "380 W Ashlan Ave. Clovis, CA 93612",
        "email": "carashiro@fresnocountyca.gov",
        "phone": "(559) 600-2485",
        "note": ""
      },
      {
        "programs": "Fresno County ILP Website",
        "name": "Fresno County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Glenn",
    "confirmed": "Confirmed 4/28/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Matt Doyle",
        "title": "CWS Program Manager",
        "address": "604 E. Walker Street Orland, CA 95963",
        "email": "mdoyle@countyofglenn.net",
        "phone": "(530) 934-1522",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Mindy Lunsford",
        "title": "Social Worker Supervisor II",
        "address": "604 E. Walker Street Orland, CA 95963",
        "email": "mlunsford@countyofglenn.net",
        "phone": "(530) 934-1553",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "T.J. Grundy",
        "title": "At Risk Youth Coordinator-Foster Youth Services",
        "address": "Glenn County Office of Education 418 Walker Street Orland, CA 95963",
        "email": "tjgrundy@glenncoe.org",
        "phone": "(530) 934-6575 ext. 3176",
        "note": ""
      },
      {
        "programs": "Glen County Foster Youth Page",
        "name": "Glenn County Foster Youth Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Humboldt",
    "confirmed": "Updated 8/6/2025",
    "contacts": [
      {
        "programs": "ILP, THP",
        "name": "Erica Carrillo",
        "title": "Independent Living Skills Coordinator",
        "address": "433 M Street, Eureka, CA 95501",
        "email": "CWSILS@Co.Humboldt.CA.US",
        "phone": "(707) 382-4520",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Melinda Lewis",
        "title": "Extended Foster Care & Independent Living Skills Supervisor",
        "address": "433 M Street, Eureka, CA 95501",
        "email": "CWSILS@Co.Humboldt.CA.US",
        "phone": "(707) 382-4520",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Kelsey Reedy",
        "title": "ILS Coordinator",
        "address": "433 M Street Eureka, CA 95502",
        "email": "CWSILS@Co.Humboldt.CA.US",
        "phone": "(707) 382-4520",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Julie Perata",
        "title": "Staff Services Analyst",
        "address": "433 M Street Eureka, CA 95502",
        "email": "jperata@co.humboldt.ca.us",
        "phone": "(707) 298-8173",
        "note": ""
      },
      {
        "programs": "Humboldt County ILP Website",
        "name": "Humboldt County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Imperial",
    "confirmed": "Confirmed 9/3/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Brenda Lopez",
        "title": "Social Worker Supervisor / Independent Living Program (ILP)",
        "address": "2995 South 4th Street, Suite 101 El Centro, CA 92243",
        "email": "Brendalopez@co.imperial.ca.us",
        "phone": "Desk: (760) 335-3485 Cell: (760) 996-8657",
        "note": "Primary contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Malena Cochran",
        "title": "ILP Program Manager",
        "address": "2995 South 4th Street El Centro, CA 92243",
        "email": "malenacochran@co.imperial.ca.us",
        "phone": "(760) 336-3949",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Yessenia Partida",
        "title": "Program Manager-ILP & TAY Service Provider",
        "address": "2995 South 4th Street El Centro, CA 92243",
        "email": "ypartida@ivrop.org",
        "phone": "(760) 337-5079",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Maria Lopez Pantoja",
        "title": "Coordinator- Family Development and Stabilization Services",
        "address": "687 State Street El Centro, CA 92243",
        "email": "Mpantoja@ivrop.org",
        "phone": "(760) 482-3109",
        "note": ""
      },
      {
        "programs": "No County specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Inyo",
    "confirmed": "Confirmed 5/29/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Holly De Vincent",
        "title": "Program Manager of Adult and Children Services",
        "address": "1360 N. Main Street, Suite 203 B Bishop, California 93514",
        "email": "hdevincent@inyocounty.us",
        "phone": "(760) 872-1727",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Darcia Blackdeer-Lent",
        "title": "Director of Social and Placement Services",
        "address": "1360 N. Main Street, Suite 203 B Bishop, California 93514",
        "email": "dblackdeerlent@inyocounty.us",
        "phone": "(760) 872-1727",
        "note": ""
      }
    ]
  },
  {
    "county": "Kern",
    "confirmed": "Updated 4/27/2026",
    "contacts": [
      {
        "programs": "EFC, THP",
        "name": "Johannah Isaacs",
        "title": "Program Specialist",
        "address": "100 E California Ave Bakersfield, CA 93307",
        "email": "isaacsj@kerndhs.com",
        "phone": "(661) 636-4965",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Beatriz Hernandez Toro",
        "title": "EFC Supervisor",
        "address": "100 E California Ave Bakersfield, CA 93307",
        "email": "torob@kerndhs.com",
        "phone": "(661) 636-4970",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Robin Chambers",
        "title": "ILP Supervisor",
        "address": "100 E California Ave Bakersfield, CA 93307",
        "email": "chamber@kerndhs.com",
        "phone": "Office: (661) 636-4971 Cell: (661) 556-0293",
        "note": ""
      },
      {
        "programs": "Kern County ILP Website",
        "name": "Kern County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Kings",
    "confirmed": "Confirmed 8/6/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Ambar Castillo",
        "title": "Program Manager",
        "address": "1400 W. Lacey Blvd #8 Hanford, CA 93230",
        "email": "ambar.castillo@co.kings.ca.us",
        "phone": "(559) 852-2185",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Jose Rodriguez",
        "title": "Social Services Supervisor",
        "address": "1400 W Lacey Blvd, Bldg. #8 Hanford CA 93230",
        "email": "jose.rodriguez@co.kings.ca.us",
        "phone": "(559) 852-2330",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Lake",
    "confirmed": "Confirmed 3/2/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Nick Gancayco",
        "title": "Social Worker Supervisor",
        "address": "926 South Forbes Street Lakeport, CA 95453",
        "email": "nickolas.gancayco@lakecountyca.gov",
        "phone": "(707) 262-0235",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Kim Costa",
        "title": "Program Manager",
        "address": "926 South Forbes Street Lakeport, CA 95453",
        "email": "kim.costa@lakecountyca.gov",
        "phone": "(707) 262-4546",
        "note": ""
      }
    ]
  },
  {
    "county": "Lassen",
    "confirmed": "Updated 9/3/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Katherine Nielson",
        "title": "Social Worker Supervisor",
        "address": "1600 Chestnut St. Susanville, CA 96130",
        "email": "KNielson@co.lassen.ca.us",
        "phone": "(530) 251-8415",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Jennifer Quinton",
        "title": "Case Coordinating Supervisor",
        "address": "2950 Riverside Dr., Suite 101 Susanville, CA 96130",
        "email": "JQuinton@co.lassen.ca.us",
        "phone": "(530) 251-2617",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Jayson Vial",
        "title": "Director of Community Social Services",
        "address": "1400 Chestnut St, Suite A Susanville CA 96130",
        "email": "jvial@co.lassen.ca.us",
        "phone": "(530) 251-2683",
        "note": ""
      },
      {
        "programs": "Lassen County ILP Website",
        "name": "Lassen County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Los Angeles",
    "confirmed": "Confirmed 2/20/2026",
    "contacts": [
      {
        "programs": "EFC, THP",
        "name": "Zaneta Smith",
        "title": "Division Chief, Supportive Housing Division",
        "address": "1933 S. Broadway Los Angeles, CA 90007",
        "email": "SmithZ2@dcfs.lacounty.gov",
        "phone": "(213) 763-4512",
        "note": "Primary contact"
      },
      {
        "programs": "EFC, THP",
        "name": "Michael Scoggins",
        "title": "Children's Services Administrator for Transitional Age Youth",
        "address": "1933 S. Broadway Los Angeles, CA 90007",
        "email": "Scoggm@dcfs.lacounty.gov",
        "phone": "(213) 763-9334",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Go to the LA County ILP website. On the left-hand side click on \"Contact Us\" then open the \"Independent Living Program\" button for a list of contacts.",
        "title": "LA County ILP Online Website",
        "address": "",
        "email": "",
        "phone": "",
        "note": "Call or email us. If you email, please let us know your name, date of birth, how to contact you and what we can do to assist you."
      }
    ]
  },
  {
    "county": "Madera",
    "confirmed": "Updated 11/12/2025",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Danine Saff",
        "title": "Social Worker Supervisor",
        "address": "1610 Sunrise Ave Madera, CA 93638",
        "email": "danine.saff@maderacounty.com",
        "phone": "desk: 559-395-0253 cell: 559-517-6255",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Marin",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Sophie Eckert",
        "title": "Program Director / ILP Coordinator",
        "address": "Alternative Family Services 361 Third Street, Suite G San Rafael, CA 94901",
        "email": "seckert@afs4kids.org",
        "phone": "(510) 407-9800",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Nicole Brouillet",
        "title": "Case Manager",
        "address": "Alternative Family Services 361 Third Street, Suite G San Rafael, CA 94901",
        "email": "nbrouillet@afs4kids.org",
        "phone": "(415) 889-0326",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Rosa Colin Vasquez",
        "title": "",
        "address": "Alternative Family Services 361 Third Street, Suite G San Rafael, CA 94901",
        "email": "rcolinvasquez@afs4kids.org",
        "phone": "(510) 407-8715",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Jenna Milligan",
        "title": "Case Manager",
        "address": "Alternative Family Services 361 Third Street, Suite G San Rafael, CA 94901",
        "email": "jmilligan@afs4kids.org",
        "phone": "(415) 847-8990",
        "note": ""
      },
      {
        "programs": "THP",
        "name": "Abigail Gonzalez",
        "title": "Caseworker for THP NMD",
        "address": "Alternative Family Services 361 Third Street, Suite G San Rafael, CA 94901",
        "email": "agonzalez@afs4kids.org",
        "phone": "(707) 806-7311",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Jennie Day",
        "title": "Program Manager",
        "address": "3250 Kerner Blvd San Rafael, Ca. 94901",
        "email": "jennie.day@marincounty.gov",
        "phone": "(415) 473-6976",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Mariposa",
    "confirmed": "Updated 4/27/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "ILP Team Email Inbox",
        "title": "HHSAILP@mariposacounty.gov",
        "address": "",
        "email": "HHSAILP@mariposacounty.gov",
        "phone": "",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Kaitlin Pasma",
        "title": "Social Worker Supervisor, ILP & THP Plus Coordinator",
        "address": "Physical address: 5362 Lemee Lane Mariposa, CA 95338 Mailing address: PO Box 99 Mariposa, CA 95338",
        "email": "kpasma@mariposacounty.gov",
        "phone": "(209) 742-0905",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Katherine Coggin",
        "title": "Program Administrator",
        "address": "Physical address: 5362 Lemee Lane Mariposa, CA 95338 Mailing address: PO Box 99 Mariposa, CA 95338",
        "email": "kcoggin@mariposacounty.gov",
        "phone": "(209) 742-0962",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Tina McLaughlin",
        "title": "Social Worker III",
        "address": "Physical address: 5362 Lemee Lane Mariposa, CA 95338 Mailing address: PO Box 99 Mariposa, CA 95338",
        "email": "Tmclaughlin@mariposacounty.gov",
        "phone": "(209) 742-0809",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Jessica Jenkins",
        "title": "EFC Coordinator",
        "address": "Physical address: 5362 Lemee Lane Mariposa, CA 95338 Mailing address: PO Box 99 Mariposa, CA 95338",
        "email": "Jjenkins@mariposacounty.gov",
        "phone": "(209) 742-0816",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Mendocino",
    "confirmed": "Updated 5/29/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Lindsey Coke",
        "title": "Social Work Supervisor",
        "address": "727 S. State Street Ukiah, CA 95482",
        "email": "CokeL@mendocinocounty.gov",
        "phone": "(707) 467-5893",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Anne Nava",
        "title": "Senior Program Manager",
        "address": "727 S. State Street Ukiah, CA 95482",
        "email": "navaa@mendocinocounty.gov",
        "phone": "(707) 463-7990",
        "note": ""
      },
      {
        "programs": "Mendocino County ILP Web Page",
        "name": "Mendocino County ILP Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Merced",
    "confirmed": "Confirmed 9/3/2026",
    "contacts": [
      {
        "programs": "EFC, THP",
        "name": "Maribel Garcia Padilla",
        "title": "Core Program Director",
        "address": "3360 N Highway 59, Suite G. Merced, CA 95348",
        "email": "mgarciapadilla@aspiranet.org",
        "phone": "(209) 725-2125 ext. 7542 Aspiranet main: (209) 725-2125",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Jasmine Bungcayo",
        "title": "Supervisor ILP",
        "address": "Main Street Youth Center 1577 W. Main Street Merced, CA 95340",
        "email": "jasmine.bungcayao@countyofmerced.com",
        "phone": "(209) 385-3000 ext. 5160",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Amardip Basra",
        "title": "Program Administrator",
        "address": "2115 W. Wardrobe Ave. Merced, CA 95340",
        "email": "Amardip.Basra@countyofmerced.com",
        "phone": "(209) 385-3000 ext. 5075",
        "note": ""
      },
      {
        "programs": "Merced County ILP Website",
        "name": "Merced County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Modoc",
    "confirmed": "5/29/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Debbie Bagwell",
        "title": "County ILP Coordinator",
        "address": "120 N Main St Alturas, CA 96101",
        "email": "debbiebagwell@co.modoc.ca.us",
        "phone": "(530) 233-6501",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Tom Sandage",
        "title": "Director of Social Services",
        "address": "120 N Main St Alturas, CA 96101",
        "email": "tomsandage@co.modoc.ca.us",
        "phone": "(530) 233-6501",
        "note": ""
      }
    ]
  },
  {
    "county": "Mono",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Kyla Griffin",
        "title": "Fiscal and Administrative Officer",
        "address": "Mailing Address: PO Box 2969 Mammoth Lakes, CA 93546 Physical Address: 1290 Tavern Rd. Mammoth Lakes, CA 93546",
        "email": "kgriffin@mono.ca.gov",
        "phone": "(530) 495-1262",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Leslie Gaunt",
        "title": "Children’s Services Program Manager",
        "address": "Mailing Address: PO Box 2969 Mammoth Lakes, CA 93546 Physical Address: 1290 Tavern Rd. Mammoth Lakes, CA 93546",
        "email": "lgaunt@mono.ca.gov",
        "phone": "(760) 924-1726",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Laura Hafner",
        "title": "Social Worker Supervisor",
        "address": "Mailing Address: PO Box 2969 Mammoth Lakes, CA 93546 Physical Address: 1290 Tavern Rd. Mammoth Lakes, CA 93546",
        "email": "lhafner@mono.ca.gov",
        "phone": "(760) 924-1784",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Monterey",
    "confirmed": "Confirmed 5/29/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Primary contact - email or phone",
        "title": "",
        "address": "",
        "email": "501-fcs-ilp@countyofmonterey.gov",
        "phone": "(831) 755-4475 – Ask to speak to the supervisor of the Permanency Planning Unit.",
        "note": "Please use this as primary contact information."
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Chelsea Chacon",
        "title": "Management Analyst III",
        "address": "1000 South Main Street, Suite 205 Salinas, CA 93901",
        "email": "ChaconC@countyofmonterey.gov",
        "phone": "(831) 755-8596",
        "note": "Secondary / backup contact"
      },
      {
        "programs": "ILP Website",
        "name": "Hartnell College / Monterey County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Napa",
    "confirmed": "Confirmed 9/4/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Rebecca Vega",
        "title": "ILP Case Manager",
        "address": "Voices Youth Center 780 Lincoln Ave. Napa, CA 94558",
        "email": "rebecca@voicesyouthcenter.org",
        "phone": "(707) 307-9322",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Alessandra Klein",
        "title": "Staff Services Analyst",
        "address": "2751 Napa Valley Corporate Dr Bldg. B Napa, CA 94558",
        "email": "Alessandra.Klein@countyofnapa.org",
        "phone": "(707) 224-8541",
        "note": ""
      }
    ]
  },
  {
    "county": "Nevada",
    "confirmed": "Confirmed 6/1/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Melissa Balderston",
        "title": "Independent Living Program Coordinator",
        "address": "380 Crown Point Circle Grass Valley, CA 95945",
        "email": "mbalderston@nevco.org",
        "phone": "(530) 470-8510 ext. 2020",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Helena Heinzelman",
        "title": "Program Specialist",
        "address": "380 Crown Point Circle Grass Valley, CA 95945",
        "email": "HHeinzelman@nevco.org",
        "phone": "(530) 557-0976",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "Foster Youth Services - Nevada County Superintendent of Schools",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Orange",
    "confirmed": "Updated 3/2/2026",
    "contacts": [
      {
        "programs": "ILP, THP",
        "name": "Shannon Hickman",
        "title": "Senior Social Services Supervisor",
        "address": "800 N. Eckhoff Street Orange, CA 92868",
        "email": "Shannon.Hickman@ssa.ocgov.com",
        "phone": "(714) 342-3791",
        "note": "Primary contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Deborah Mathy",
        "title": "Senior Human Services Manager",
        "address": "800 N. Eckhoff Street Orange, CA 92868",
        "email": "deborah.mathy@ssa.ocgov.com",
        "phone": "Office: (714) 940-5610 Cell: (714) 913-3593",
        "note": "Secondary / backup contact"
      },
      {
        "programs": "ILP, EFC",
        "name": "Natalie Hay",
        "title": "Senior Social Services Supervisor",
        "address": "800 N. Eckhoff Street Orange, CA 92868",
        "email": "Natalie.Hay@ssa.ocgov.com",
        "phone": "(714) 697-9321",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Laura Yescas",
        "title": "Senior Social Services Supervisor",
        "address": "800 N. Eckhoff Street Orange, CA 92868",
        "email": "laura.yescas@ssa.ocgov.com",
        "phone": "Office: (714) 940-3936 Cell: (714) 394-2132",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Natalie Arellano",
        "title": "Senior Social Services Supervisor",
        "address": "800 N. Eckhoff Street Orange, CA 92868",
        "email": "Natalie.Arellano@ssa.ocgov.com",
        "phone": "(714) 380-8359",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "Orange County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Placer",
    "confirmed": "Updated 6/8/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Michelle Graf",
        "title": "Contracted ILP Coordinator (Placer County Office of Education)",
        "address": "Placer County Office of Education (PCOE) 1400 W. Stanford Ranch Road Rocklin, CA 95765",
        "email": "mgraf@placercoe.org",
        "phone": "(279) 262-2349",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Miranda Long",
        "title": "Child Welfare Program Manager",
        "address": "Placer County Children's System of Care 11434 B Avenue, Suite 300 Auburn CA 95603",
        "email": "mlong@placer.ca.gov",
        "phone": "(916) 784-6429",
        "note": ""
      },
      {
        "programs": "THP-Plus",
        "name": "Christina Nicholson (THP-Plus contact only)",
        "title": "Director",
        "address": "11816 Kemper Rd Auburn, Ca 95603",
        "email": "wplcep@pacbell.net",
        "phone": "(530) 558-5355",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "Placer County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Plumas",
    "confirmed": "Confirmed 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Heidi Hysmith (primary contact)",
        "title": "Senior Social Worker",
        "address": "270 County Hospital Road,. Suite 207 Quincy, CA 95971",
        "email": "heidihysmith@countyofplumas.com",
        "phone": "(530) 283-6469",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Melissa Smith (secondary contact)",
        "title": "Social Worker Supervisor",
        "address": "270 County Hospital Road, Suite 207 Quincy, CA 95971",
        "email": "MelissaSmith@countyofplumas.com",
        "phone": "Desk: (530) 283-6311 Cell: (530) 616-7142",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Front Desk (backup contact)",
        "title": "Ask for the worker of the day.",
        "address": "270 County Hospital Road,. Suite 207 Quincy, CA 95971",
        "email": "",
        "phone": "(530) 283-6350",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP web page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Riverside",
    "confirmed": "Confirmed 9/3/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "THP and ILP Hotline Email and Phone Number",
        "title": "ILP@rivco.org",
        "address": "(951) 358-6748",
        "email": "ILP@rivco.org",
        "phone": "(951) 358-6748",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Lydia Brown",
        "title": "ILP Coordinator Program Specialist",
        "address": "10281 Kidd Street, 2nd Floor Riverside, CA 92503",
        "email": "LyBrown@rivco.org",
        "phone": "(951) 445-7923",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Emilee Tran",
        "title": "Regional Manager",
        "address": "23119 Cottonwood Ave., Bldg. B., 1st Floor Moreno Valley, CA 92553",
        "email": "emtran@rivco.org",
        "phone": "(951) 232-7571",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Noelia Sanchez",
        "title": "Regional Manager",
        "address": "23119 Cottonwood Ave., Bldg. B., 1st Floor Moreno Valley, CA 92553",
        "email": "Nosanche@rivco.org",
        "phone": "(951) 413-5231",
        "note": ""
      },
      {
        "programs": "Riverside Youth web page",
        "name": "Riverside County Youth and Young Adult Programs",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Sacramento",
    "confirmed": "Confirmed 5/29/2026",
    "contacts": [
      {
        "programs": "ILP Email Address",
        "name": "ILP@saccounty.gov",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Stephanie Sandmeier",
        "title": "Program Planner",
        "address": "P.O. Box 269057 Sacramento, CA 95826",
        "email": "sandms@saccounty.gov",
        "phone": "(916) 875-6993",
        "note": "Primary contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Edward Fernando",
        "title": "Program Manager",
        "address": "P.O. Box 269057 Sacramento, CA 95826",
        "email": "fernae@saccounty.gov",
        "phone": "(916) 874-5104",
        "note": "Secondary / backup contact"
      },
      {
        "programs": "ILP Website",
        "name": "Sacramento County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "San Benito",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "EFC, THP, ILP",
        "name": "Joshua Mercier",
        "title": "Deputy Director",
        "address": "Health and Human Services 1111 San Felipe Rd, Suite 205 Hollister, CA 95023",
        "email": "JMercier@sanbenitocountyca.gov",
        "phone": "Desk: (831) 902-2563 Main Office: (831) 636-4190",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP web page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "San Bernardino",
    "confirmed": "Updated 7/8/2026",
    "contacts": [
      {
        "programs": "ILP or THP INQUIRIES",
        "name": "Transitional Housing / ILP mailbox",
        "title": "CFSILP@hss.sbcounty.gov",
        "address": "Mailbox for foster youth inquiries",
        "email": "CFSILP@hss.sbcounty.gov",
        "phone": "",
        "note": "Mailbox for THP or ILP inquiries"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Laquisha Mcgeilberry",
        "title": "Social Worker II",
        "address": "1495 S. E Street San Bernardino Ca 92408",
        "email": "Laquisha.McGeilberry@hss.sbcounty.gov",
        "phone": "Desk: (909) 891-3366 Cell: (909) 723-7731",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Deborah Baeza",
        "title": "Placement Support Unit Supervisor",
        "address": "1495 S. E Street San Bernardino Ca 92408",
        "email": "deborah.baeza@hss.sbcounty.gov",
        "phone": "(909) 891-3534",
        "note": ""
      },
      {
        "programs": "THP (information for homeless youth)",
        "name": "Guide to Homeless Service Providers",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Monique Ware",
        "title": "ILP Coordinator",
        "address": "1495 S. E Street San Bernardino Ca 92408",
        "email": "monique.ware@hss.sbcounty.gov",
        "phone": "(909) 677-9640",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Lizbeth Corrales",
        "title": "ILP Supervisor",
        "address": "1495 S. E Street San Bernardino Ca 92408",
        "email": "Lizbeth.Corrales@hss.sbcounty.gov",
        "phone": "(909) 891-3383",
        "note": ""
      },
      {
        "programs": "County ILP Web Page",
        "name": "San Bernardino County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "THP (for providers)",
        "name": "Housing provider mailbox",
        "title": "",
        "address": "Mailbox for transitional housing provider inquiries",
        "email": "strtp@hss.sbcounty.gov",
        "phone": "",
        "note": "For potential Transitional Housing provider inquiries"
      }
    ]
  },
  {
    "county": "San Diego",
    "confirmed": "Updated 2/11/2026",
    "contacts": [
      {
        "programs": "THP",
        "name": "Gloria Salgado",
        "title": "Program Specialist II",
        "address": "8965 Balboa Ave San Diego Ca 92123",
        "email": "Gloria.Salgado@sdcounty.ca.gov",
        "phone": "Desk: (858) 614-9190 Cell: (858) 740-8195",
        "note": "She covers all areas of Transitional Housing for Youth"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Daniel Bernal",
        "title": "Program Manager - EFC/ILP",
        "address": "8965 Balboa Ave San Diego Ca 92123",
        "email": "Daniel.Bernal@sdcounty.ca.gov",
        "phone": "Desk: (858) 944-6019 Cell: (619) 892-2877",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "San Diego ILP Program main contact emailbox and phone",
        "title": "ILS.HHSA@sdcounty.ca.gov",
        "address": "",
        "email": "ILS.HHSA@sdcounty.ca.gov",
        "phone": "(866) 457-4636",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Julia Diaz",
        "title": "ILS Supervisor",
        "address": "8965 Balboa Ave San Diego, CA 92123",
        "email": "Julia.Diaz@sdcounty.ca.gov",
        "phone": "Desk: (858) 944-6006 Cell: (619) 405-0033",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Marie Hommel",
        "title": "Chief of Agency Operations",
        "address": "8965 Balboa Ave San Diego, CA 92123",
        "email": "Marie.Hommel@sdcounty.ca.gov",
        "phone": "(760) 421-9991",
        "note": ""
      }
    ]
  },
  {
    "county": "San Francisco",
    "confirmed": "Updated 4/3/2026",
    "contacts": [
      {
        "programs": "EFC, THP",
        "name": "Jessica Mateu-Newsome, MSW",
        "title": "Program Director, Family & Children Services",
        "address": "P.O. Box 7988 San Francisco, CA 94120-7988",
        "email": "Jessica.Mateu-Newsome@sfgov.org",
        "phone": "(415) 557-5179",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Patrick Kramer",
        "title": "Admin Assistant",
        "address": "P.O. Box 7988 San Francisco, CA 94120-7988",
        "email": "Patrick.kramer@sfgov.org",
        "phone": "(415) 557-5406",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Erica Waterford",
        "title": "Vice President Program",
        "address": "First Place for Youth 426 17th Street, Suite 100 Oakland, CA 94612",
        "email": "ewaterford@firstplaceforyouth.org",
        "phone": "(510) 648-3543",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Amy Freer",
        "title": "Program Support Analyst",
        "address": "P.O. Box 7988 San Francisco, CA 94120-7988",
        "email": "amy.freer@sfgov.org",
        "phone": "(415) 264-4645",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Vlada Gulchin",
        "title": "Acting Program Manager",
        "address": "P.O. Box 7988 San Francisco, CA 94120-7988",
        "email": "vladlena.gulchin@sfgov.org",
        "phone": "(415) 798-0432",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "San Francisco County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "San Joaquin",
    "confirmed": "Confirmed 6/1/2026",
    "contacts": [
      {
        "programs": "EFC (primary EFC contact)",
        "name": "Tasha Gaines",
        "title": "Social Work Supervisor II",
        "address": "Physical address: 102 S. San Joaquin St. Stockton CA 95202 Mailing address: PO Box 201056 Stockton, CA 95201",
        "email": "tgaines@sjgov.org",
        "phone": "(209) 468-1064",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Cynthia Lederle",
        "title": "ILP Coordinator",
        "address": "Physical address: 102 S. San Joaquin St. Stockton CA 95202 Mailing address: PO Box 201056 Stockton, CA 95201",
        "email": "clederle@sjgov.org",
        "phone": "(209) 468-1028",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "San Joaquin County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "San Luis Obispo",
    "confirmed": "Updated 5/292026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Sandra Jiminez",
        "title": "County Contact for EFC, ILP, THP",
        "address": "3433 S Higuera St San Luis Obispo, CA 93401",
        "email": "sjiminez@co.slo.ca.us",
        "phone": "(805) 781-1841",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Darci Rice",
        "title": "Director of Programs: FFA, THPP, EFC, ILP",
        "address": "Family Care Network, Inc. 1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "drice@fcni.org",
        "phone": "(805) 602-8550",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Brian Redin",
        "title": "Director of Programs - FFA/THPP/ILP",
        "address": "Family Care Network, Inc. 1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "bredin@fcni.org",
        "phone": "(805) 801-9729",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Monica Huckleberry",
        "title": "ILP Supervisor",
        "address": "Family Care Network, Inc. 1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "Mhuckleberry@fcni.org",
        "phone": "(805) 792-4005",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Taylor Brooks",
        "title": "Manager of Program",
        "address": "Family Care Network, Inc. 1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "TBrooks@fcni.org",
        "phone": "(805) 952-9474",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "San Luis Obispo ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "San Mateo",
    "confirmed": "Confirmed 4/27/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Transitional Housing / ILP Mailbox",
        "title": "hsa_ilp_referrals@smcgov.org",
        "address": "Use this mailbox as primary contact method.",
        "email": "hsa_ilp_referrals@smcgov.org",
        "phone": "",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Emilia Jones Lewis",
        "title": "Program Manager",
        "address": "2500 Middlefield Rd. Redwood City, CA 94063",
        "email": "EJones@smcgov.org",
        "phone": "(650) 363-4558",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Jeremy Latta",
        "title": "Social Worker Supervisor",
        "address": "2415 University Ave, 3rd Floor E. Palo Alto, CA 94303",
        "email": "jlatta@smcgov.org",
        "phone": "(650) 599-5981",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Sandy Barba",
        "title": "ILP Coordinator / Social Worker",
        "address": "2415 University Ave, 3rd Floor E. Palo Alto, CA 94303",
        "email": "sbarba@smcgov.org",
        "phone": "(650) 599-5944",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Steve Axberg",
        "title": "ILP Case Manager",
        "address": "2415 University Ave, 3rd Floor E. Palo Alto, CA 94303",
        "email": "saxberg@smcgov.org",
        "phone": "(650) 599-5911",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Guadalupe Palomino",
        "title": "ILP Case Manager",
        "address": "2415 University Ave, 3rd Floor E. Palo Alto, CA 94303",
        "email": "gpalomino@smcgov.org",
        "phone": "(650) 599-5958",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "San Mateo County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Santa Barbara",
    "confirmed": "Updated 5/29/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Melissa Rodriguez",
        "title": "Social Services Supervisor",
        "address": "234 Camino del Remedio Santa Barbara, CA 93110",
        "email": "mrodr3@countyofsb.org",
        "phone": "(805) 681-4558",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Darci Rice",
        "title": "Director of Programs FFA, THPP, EFC, ILP",
        "address": "1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "drice@fcni.org",
        "phone": "(805) 602-8550",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Brian Redin",
        "title": "Director of Programs - FFA/THPP/ILP",
        "address": "1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "bredin@fcni.org",
        "phone": "(805) 801-9729",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Monica Huckleberry",
        "title": "ILP Supervisor",
        "address": "Family Care Network, Inc. 1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "Mhuckleberry@fcni.org",
        "phone": "(805) 792-4005",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Taylor Brooks",
        "title": "Manager of Program",
        "address": "Family Care Network, Inc. 1255 Kendall Road San Luis Obispo, CA 93401",
        "email": "TBrooks@fcni.org",
        "phone": "(805) 952-9474",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "Santa Barbara County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Santa Clara",
    "confirmed": "Confirmed 9/3/2026",
    "contacts": [
      {
        "programs": "EFC, THP",
        "name": "Lea Balatbat",
        "title": "Social Work Supervisor of the Non-Minor Dependent (NMD) Unit",
        "address": "353 W. Julian St. San Jose, CA 95110",
        "email": "lea.balatbat@ssa.sccgov.org,",
        "phone": "(408) 793-8889",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Cecilia Roman",
        "title": "Social Work Supervisor, Non Minor Dependent (NMD) Unit",
        "address": "353 W. Julian St. San Jose, CA 95110",
        "email": "cecilia.roman@ssa.sccgov.org",
        "phone": "(408) 501-6785",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Marisela Martinez",
        "title": "Social Service Program Manager II",
        "address": "353 W. Julian St. San Jose, CA 95110",
        "email": "marisela.martinez@ssa.sccgov.org",
        "phone": "(408) 501- 6839",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Marixa Valencia (for THP-M, THP-NMD)",
        "title": "Social Worker Supervisor",
        "address": "353 W. Julian St. San Jose, CA 95110",
        "email": "marixa.valencia01@ssa.sccgov.org",
        "phone": "(408) 792-1839",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Marisela Duenas (intake for THP-M and THP-NMD)",
        "title": "THPP/THP-NMD Social Worker",
        "address": "353 W. Julian St. San Jose, CA 95110",
        "email": "Marisela.Duenas@ssa.sccgov.org",
        "phone": "(408) 501-6858",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Temera Carson (for THP-M, THP-NMD)",
        "title": "Social Services Program Manager II",
        "address": "353 W. Julian St. San Jose, CA 95110",
        "email": "temera.carson@ssa.sccgov.org",
        "phone": "(408) 501-6713",
        "note": ""
      },
      {
        "programs": "THP",
        "name": "St. Andrew's Residential Program (S.T.A.R)",
        "title": "THP-NMD Program",
        "address": "811 Sherman Oaks Drive San Jose, CA 95128",
        "email": "\"Contact Us\" online form available on the website",
        "phone": "(408) 501-6643",
        "note": ""
      },
      {
        "programs": "THP",
        "name": "Santa Clara County First Place for Youth",
        "title": "First Place for Youth Home Page",
        "address": "",
        "email": "",
        "phone": "(408) 500-5162",
        "note": "For youths from outside of Santa Clara County jurisdiction seeking transitional housing in Santa Clara County"
      },
      {
        "programs": "THP",
        "name": "Bill Wilson Center",
        "title": "",
        "address": "",
        "email": "",
        "phone": "((669) 230-4015",
        "note": ""
      },
      {
        "programs": "ILP emailbox and phone number",
        "name": "ilpinfo@ssa.sccgov.org",
        "title": "Phone: (408) 501-6866",
        "address": "",
        "email": "",
        "phone": "phone: (408) 501-6866 text: (877) 975-1225",
        "note": "Primary contact for ILP"
      },
      {
        "programs": "ILP",
        "name": "Patricia Martinez",
        "title": "ILP Social Services Analyst",
        "address": "1510 Parkmoor Avenue, Suite 101 San Jose, CA 95128",
        "email": "Patricia.Martinez01@ssa.sccgov.org",
        "phone": "(669) 252-5037",
        "note": ""
      },
      {
        "programs": "ILP, THP",
        "name": "Cindy Guillen",
        "title": "Social Services Program Manager I",
        "address": "1510 Parkmoor Avenue, Suite 101 San Jose, CA 95128",
        "email": "cindy.guillen@ssa.sccgov.org",
        "phone": "(408) 502-1868",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Marisela Martinez",
        "title": "TAY Project Manager",
        "address": "353 W. Julian St. San Jose, CA 95110",
        "email": "marisela.martinez@ssa.sccgov.org",
        "phone": "(408) 501-6839",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "Santa Clara County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Santa Cruz",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Rene Fuentes",
        "title": "Program Coordinator, Encompass Community Services",
        "address": "120 Dubois St, Suite A Santa Cruz, CA 95060",
        "email": "Rene.Fuentes@encompasscs.org",
        "phone": "(831) 889-0561",
        "note": "Primary Contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Lucero Parra",
        "title": "Social Work Supervisor",
        "address": "1400 Emeline Avenue Santa Cruz, CA 95060",
        "email": "Lucero.Parra@santacruzcountyca.gov",
        "phone": "(831) 763-8446",
        "note": "Backup Contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Deborah Bresnick",
        "title": "Program Manager",
        "address": "1400 Emeline Avenue Santa Cruz, CA 95060",
        "email": "Deborah.Bresnick@santacruzcountyca.gov",
        "phone": "(831) 454-4285",
        "note": "Backup Contact"
      },
      {
        "programs": "TAY / ILP web page",
        "name": "TAY (Transition Age Youth) - Encompass Community Services",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Shasta",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Valerie Hartley",
        "title": "ILP Coordinator",
        "address": "2770 Pioneer Drive Redding, CA 96001",
        "email": "vhartley@youthandfamily.info",
        "phone": "(530) 365-9197",
        "note": "Primary contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Crystal Adams",
        "title": "Program Manager",
        "address": "1550 California St. Redding, CA 96001",
        "email": "cmadams@shastacounty.gov",
        "phone": "(530) 225-5491",
        "note": "Secondary / backup contact"
      },
      {
        "programs": "ILP Web Page",
        "name": "Shasta County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Sierra",
    "confirmed": "Updated 4/13/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Lori McGee",
        "title": "Director of Social Services / Public Guardian",
        "address": "P.O. Box 1019 Loyalton, CA 96118",
        "email": "lmcgee@sierracounty.ca.gov",
        "phone": "(530) 993-6720",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Jamie Shiltz",
        "title": "Social Worker Supervisor/ ILP Coordinator",
        "address": "P.O. Box 1019 Loyalton, CA 96118",
        "email": "jshiltz@sierracounty.ca.gov",
        "phone": "(530) 993-6732",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Siskiyou",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Michael Werder",
        "title": "ILP Coordinator",
        "address": "2060 Campus Dr. Yreka, CA 96097",
        "email": "mwerder@co.siskiyou.ca.us",
        "phone": "(530) 841-4779",
        "note": "Primary Contact"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Corina Long",
        "title": "Program Supervisor",
        "address": "2060 Campus Dr. Yreka, CA 96097",
        "email": "colong@co.siskiyou.ca.us",
        "phone": "(530) 841-4200",
        "note": "Backup Contact"
      },
      {
        "programs": "Transitional Housing Provider",
        "name": "Contact Children First Foster Family Agency Contacts Page",
        "title": "Children First Foster Family Agency Home Page",
        "address": "525 N. Main St. Yreka, CA 96097",
        "email": "",
        "phone": "(530) 841-1030",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Solano",
    "confirmed": "Confirmed 5/29/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Angel Reese-Galloway",
        "title": "Social Services Supervisor",
        "address": "275 Beck Ave. Fairfield, CA 94533",
        "email": "AMReeseGalloway@solanocounty.gov",
        "phone": "(707) 784-8446",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Margaret Friel",
        "title": "Social Services Manager",
        "address": "275 Beck Ave. Fairfield, CA 94533",
        "email": "Frielm@solanocounty.gov",
        "phone": "(707) 784-8497",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Susan Kimball",
        "title": "ILSP Manager, First Place for Youth",
        "address": "1545 N. Texas St., Suite 100 Fairfield, CA 94533",
        "email": "skimball@firstplaceforyouth.org",
        "phone": "Desk: (707) 430-4360 ext. 4363 Cell: (916) 213-5575",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Sonoma",
    "confirmed": "Updated 3/27/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Andres Cantera",
        "title": "ILP Coordinator",
        "address": "718 Lincoln Ave. Napa CA 94558",
        "email": "andres@voicesyouthcenter.org",
        "phone": "Desk: (707) 251-9432 Cell: (707) 812-3766",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Stephenie McCollre",
        "title": "ILP Case Manager",
        "address": "2800 Cleveland Ave, Suite C Santa Rosa, CA 95403",
        "email": "stephenie@voicesyouthcenter.org",
        "phone": "(707) 579-4327",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Benjamin Rosel",
        "title": "ILP Case Manager",
        "address": "2800 Cleveland Ave, Suite C Santa Rosa, CA 95403",
        "email": "benjamin@voicesyouthcenter.org",
        "phone": "(707) 579-4327",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Vanessa Guevara",
        "title": "Transition Age Youth Housing Programs Director",
        "address": "821 Mendocino Ave. Santa Rosa, CA 95401",
        "email": "vguevara@tlc4kids.org",
        "phone": "(707) 867-8827",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Regina de Melo",
        "title": "ILP Program Development Manager",
        "address": "1202 Apollo Way Santa Rosa, CA 95402",
        "email": "rdemelo@schsd.org",
        "phone": "(707) 565-4346",
        "note": ""
      }
    ]
  },
  {
    "county": "Stanislaus",
    "confirmed": "Updated 4/21/2026",
    "contacts": [
      {
        "programs": "EFC, THP",
        "name": "Jennifer Lee",
        "title": "Core Program Director II",
        "address": "1009 10th Street Modesto, CA 95354",
        "email": "jenlee@aspiranet.org",
        "phone": "(209) 338-5444 ext. 8316",
        "note": ""
      },
      {
        "programs": "EFC, THP",
        "name": "Khoa Nguyen",
        "title": "Social Worker Supervisor II",
        "address": "PO Box 42 Modesto CA 95353",
        "email": "nguyekc@stancounty.com",
        "phone": "(209) 226-3226",
        "note": "Specifically for AB12 inquiries"
      },
      {
        "programs": "ILP",
        "name": "Erica Verduzco",
        "title": "Social Worker Supervisor II",
        "address": "PO Box 42 Modesto CA 95353",
        "email": "VerdEr@stancounty.com",
        "phone": "(209) 558-2722",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Verenis Estrada",
        "title": "ILP Supervisor",
        "address": "1009 J Street Modesto, CA 95354",
        "email": "veestrada@aspiranet.org",
        "phone": "Call main number (209) 338-5444, ask for Independent Living Program assistance.",
        "note": ""
      }
    ]
  },
  {
    "county": "Sutter",
    "confirmed": "Updated 3/16/2026",
    "contacts": [
      {
        "programs": "EFC, THP, ILP",
        "name": "Angela Castillon",
        "title": "Social Worker",
        "address": "1531-A Butte House Road Yuba City, CA 95993",
        "email": "acastillon@sutter.gov",
        "phone": "(530) 682-4597",
        "note": ""
      },
      {
        "programs": "EFC, THP, ILP",
        "name": "Bianca Silva",
        "title": "Social Worker Supervisor",
        "address": "1531-A Butte House Road Yuba City, CA 95993",
        "email": "bsilva@sutter.gov",
        "phone": "(530) 822-7151, ext. 107",
        "note": ""
      },
      {
        "programs": "Sutter County ILP Web Page",
        "name": "Independent Living Program, Sutter County",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "Sutter County THP Web Page",
        "name": "Sutter County Transitional Housing Programs (THP)",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "Sutter County CWS Web Page",
        "name": "Sutter County Child Welfare Services (CWS)",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Tehama",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Steven Dickerson",
        "title": "Child Welfare Program Manager",
        "address": "220 Sycamore Street #101 Red Bluff, CA 96080",
        "email": "SDickerson@tcdss.org",
        "phone": "(530) 528-4020",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Karen Kemp",
        "title": "Director of THP / SUD (Substance Use Disorder) Children's First Foster Family Agency",
        "address": "590 Antelope Blvd Red Bluff, CA 96080",
        "email": "kkemp@childrenfirstffa.com",
        "phone": "(530) 526-2766",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Janine LoBue",
        "title": "Youth and Family Programs",
        "address": "900 Jackson Street Red Bluff, CA 96080",
        "email": "jlobue@youthandfamily.info",
        "phone": "(530) 227-6458",
        "note": ""
      },
      {
        "programs": "Youth & Family Programs Web Page",
        "name": "Supporting Foster Families in Shasta, Tehama, and Butte Counties",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Trinity",
    "confirmed": "Confirmed 4/162026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Angela Berglund",
        "title": "Program Manager",
        "address": "Physical Address: 51 Industrial Parkway Weaverville, CA 96093 Mailing address: PO Box 1378 Weaverville, CA 96093",
        "email": "aberglund@trinitycounty.org",
        "phone": "(530) 623-8280",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Amara Robles",
        "title": "Social Worker Supervisor",
        "address": "Physical Address: 51 Industrial Parkway Weaverville, CA 96093 Mailing address: PO Box 1378 Weaverville, CA 96093",
        "email": "arobles@trinitycounty.org",
        "phone": "(530) 623-8297",
        "note": ""
      }
    ]
  },
  {
    "county": "Tulare",
    "confirmed": "Confirmed 12/22/2025",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Kimberly Weeks",
        "title": "AB12 & ILP Supervisor",
        "address": "6520 S Mooney Blvd Visalia, California 93277",
        "email": "KWeeks@tularecounty.ca.gov",
        "phone": "(559) 623-0405",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Margaret Pineda",
        "title": "Social Worker",
        "address": "6520 S Mooney Blvd Visalia, California 93277",
        "email": "MPineda@tularecounty.ca.gov",
        "phone": "(559) 623-0336",
        "note": ""
      },
      {
        "programs": "No County-specific ILP web page",
        "name": "For general information about ILP see the CDSS ILP page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Tuolumne",
    "confirmed": "Updated 7/30/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Erin Gandolfo-Brune",
        "title": "Agency Manager",
        "address": "20075 Cedar Road North Sonora, CA 95370",
        "email": "egandolfo@co.tuolumne.ca.us",
        "phone": "(209) 533-5773",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Sara Camps",
        "title": "Social Services Supervisor",
        "address": "20075 Cedar Road North Sonora, CA 95370",
        "email": "scamps@co.tuolumne.ca.us",
        "phone": "(209) 533-6831",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Cely Hess",
        "title": "ILP Coordinator",
        "address": "20075 Cedar Road North Sonora, CA 95370",
        "email": "chess@co.tuolumne.ca.us",
        "phone": "(209) 533-6858",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "Tuolumne County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Ventura",
    "confirmed": "Updated 12/18/2025",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "HSA-ILP@Ventura.org",
        "title": "(805) 654-3409, ask for the Officer of the Day",
        "address": "4561 Telephone Rd, #300 Ventura, CA 93003",
        "email": "HSA-ILP@venturacounty.gov",
        "phone": "(805) 654-3409, ask for the Officer of the Day",
        "note": "For ILP, EFC, THP inquiries"
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Noe Villa",
        "title": "Program Manager",
        "address": "4561 Telephone Rd, #300 Ventura, CA 93003",
        "email": "noe.villa@venturacounty.gov",
        "phone": "(805) 654-3444",
        "note": ""
      },
      {
        "programs": "ILP Website",
        "name": "Ventura County ILP Web Page",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Yolo",
    "confirmed": "Confirmed 2/2/2026",
    "contacts": [
      {
        "programs": "THP",
        "name": "Yolo County has no transitional housing at this time.",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      },
      {
        "programs": "ILP",
        "name": "Ramiz Ali",
        "title": "Social Worker Practitioner/ILP Coordinator",
        "address": "137 N. Cottonwood St. Woodland, CA 95695",
        "email": "Ramiz.Ali@yolocounty.org",
        "phone": "(530) 681-9219",
        "note": "Primary contact"
      },
      {
        "programs": "ILP",
        "name": "Eddie Miller",
        "title": "Transition Age Youth Supervisor",
        "address": "137 N. Cottonwood St. Woodland, CA 95695",
        "email": "Edward.Miller@yolocounty.org",
        "phone": "(530) 666-8497",
        "note": "Secondary / backup contact"
      },
      {
        "programs": "ILP Web Page",
        "name": "Yolo County Independent Living Skills Program",
        "title": "",
        "address": "",
        "email": "",
        "phone": "",
        "note": ""
      }
    ]
  },
  {
    "county": "Yuba",
    "confirmed": "Confirmed 4/6/2026",
    "contacts": [
      {
        "programs": "ILP, EFC, THP",
        "name": "Twyla Williams",
        "title": "Program Manager - Child and Adult Protective Services (CAPS)",
        "address": "Mailing Address: PO Box 2320 Marysville, CA 95901 Physical Address: 5730 Packard Ave, Suite 100 Marysville, CA 95901",
        "email": "twilliams@yuba.gov",
        "phone": "Office: (530) 749-6266 Cell: (530) 812-2389",
        "note": ""
      },
      {
        "programs": "ILP, EFC, THP",
        "name": "Lindsay Avina",
        "title": "Social Worker Supervisor – Child and Adult Protective Services",
        "address": "Mailing Address: PO Box 2320 Marysville, CA 95901 Physical Address: 5730 Packard Ave, Suite 100 Marysville, CA 95901",
        "email": "lavina@yuba.gov",
        "phone": "Office: (530) 749-6275 Cell: (530) 812-2384",
        "note": ""
      }
    ]
  }
];

export function countyByName(name: string | undefined): CountyEntry | undefined {
  if (!name) return undefined;
  return counties.find((c) => c.county.toLowerCase() === name.toLowerCase());
}
